
name: on-tag-build-and-push-image
on:
  push:
    tags:
      - '1.*'
jobs:
    build:
      timeout-minutes: 15
      runs-on: ubuntu-18.04
      steps:
        - name: Get Git Repository Info
          run: |
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
            echo "FULL_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        - name: Set Image and Container Names
          run: |
            echo "CONTAINER_NAME=${FULL_REPOSITORY#${OWNER}/}" >> $GITHUB_ENV
            echo "DOCKER_IMAGE=ghcr.io/$FULL_REPOSITORY:$TAG" >> $GITHUB_ENV
        - uses: actions/checkout@v2
        - uses: olafurpg/setup-scala@v12
          with:
            java-version: openjdk@1.9.0
        - name: Build Play Distribution
          run: ./build.sh
          working-directory: "."

